version: '2'
services:
    mysnk-db:
        container_name: mysnk-db
        image: postgres:latest
        environment:
            POSTGRES_DB: 'mysneakersdb'
            POSTGRES_PASSWORD: 'root'
            POSTGRES_USER: 'root'
        ports:
            - '5432:5432'
        volumes:
            - ./mysnk-backend:/home/backend/app
            - ./mysnk-backend/mysneakersdb/pgdata:/var/lib/postgresql
        networks:
            - mysnk-server

    mysnk-backend:
        container_name: mysnk-backend
        build: ./mysnk-backend
        restart: always
        ports:
            - 8001:8001
        depends_on:
            - mysnk-db
        env_file:
            - ./mysnk-backend/.env
        tty: true
        working_dir: /home/backend/app
        volumes:
            - ./mysnk-backend:/home/backend/app
            - ./mysnk-backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - mysnk-server

    mysnk-frontend:
        container_name: mysnk-frontend
        build: ./mysnk-frontend
        restart: always
        ports:
            - 5173:5173
        volumes:
            - ./mysnk-frontend:/home/frontend/app
        env_file:
            - ./mysnk-frontend/.env
        networks:
            - mysnk-server

    ngnix-server:
        build: ./mysnk-ngnix
        container_name: ngnix-server
        restart: always
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./mysnk-backend:/home/backend/app
            - ./mysnk-frontend:/home/frontend/app
        networks:
            - mysnk-server
        depends_on:
            - mysnk-backend
            - mysnk-frontend

networks:
    mysnk-server:
        driver: bridge
    