version: '2'
services:
    # mysnk-db:
    #     container_name: mysnk-db
    #     image: mongo:latest
    #     restart: always
    #     networks:
    #         - mysnk-back
    #     ports:
    #         - "27017:27017"
    #     volumes:
    #         - mysnk-db:/data/db

    mysnk-db:
        container_name: mysnk-db
        image: postgres:latest
        environment:
            POSTGRES_DB: 'mysneakersdb'
            POSTGRES_PASSWORD: 'root'
            POSTGRES_USER: 'root'
        ports:
            - '5432:5432'
        volumes:
            - /mysnk-backend:/var/www/html
            - ./mysnk-backend/mysneakersdb/pgdata:/var/lib/postgresql
        networks:
            - mysnk-server-back

    mysnk-backend:    
        container_name: mysnk-backend
        build: ./mysnk-backend
        restart: always
        ports:
            - 8001:8001
        depends_on:
            - mysnk-db
        env_file:
            - ./mysnk-backend/.env
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./mysnk-backend:/var/www/html
            - ./mysnk-backend/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - mysnk-server-back

    # mysnk-frontend:
    #     container_name: mysnk-frontend
    #     build: ./mysnk-frontend
    #     networks:
    #         - mysnk-front
    #     volumes:
    #         - mysnk-front:/var/www/html
    #     env_file:
    #         - ./mysnk-frontend/.env

    ngnix-server-back:
        image: nginx:alpine
        container_name: ngnix-server-back
        restart: always
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./mysnk-backend:/var/www/html
            - ./mysnk-backend/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - mysnk-server-back

networks:
    mysnk-server-back:
        driver: bridge
    # mysnk-server-front:
    #     driver: bridge

# volumes:
    # mysnk-db:
    # mysnk-front: